from AIScratch.NeuralNetwork.ActivationFunctions.function import ActivationFunction
from AIScratch.NeuralNetwork.ActivationFunctions.relu import ReLU
from AIScratch.NeuralNetwork.ActivationFunctions.treshold import Treshold