name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # actions with tag that starts with v

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # clone repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # config python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Choisissez la version de Python

      # install poetry
      - name: Install Poetry
        run: pip install poetry

      # verify poetry
      - name: Poetry version
        run: poetry --version

      # install poetry dependencies
      - name: Install dependencies
        run: poetry install

      # build package
      - name: Build package
        run: poetry build

      # publish to pypi
      - name: Publish to PyPI
        run: poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}